### ISSUE TITLE
Flutter supported the affected commands of NX ?

### ISSUE THREAD

**Issue by iangregsondev** [tinesoft/nxrocks#107]
Hi,

Great package!

Does this plugin take into consideration what app / packages have changed and it can build ONLY them ?

i..e If I have 2 libraries and 1 app and only the first library changed then it would only build that library and the main app as it depends on it.. but would not build library 2

Thanks

**Comment by tinesoft** [comment]
Hi @iangregsondev 

Thanks for your interest in the plugin!
Support for Nx`s `affected` commands has landed with [v2.1.0]( [nx-flutter/v2.1.0](https://github.com/tinesoft/nxrocks/releases/tag/nx-flutter%2Fv2.1.0)) of the plugin, thanks to the dependency graph API.
So it should work out-of-the-box.


Are you facing a particular issue?

**Comment by iangregsondev** [comment]
Great stuff. Thanks.
