### ISSUE TITLE
[Feature] Add user-agent for requests to start.spring.io

### ISSUE THREAD

**Issue by snicoll** [tinesoft/nxrocks#11]
**Is your feature request related to a problem? Please describe.**
When requesting a new project on start.spring.io, we prefer that a `User-Agent` header to be set, see [the reference guide](https://docs.spring.io/initializr/docs/current/reference/html/#metadata-format).

**Describe the idea you'd like**
A `User-Agent` to be set according to the docs for every request to the service.

**Comment by tinesoft** [comment]
Hi @snicoll!

Thanks for reaching out about this. I was indeed not aware of that guide.
I will start implementing the enhancement right away.


PS: by the way, I love ❤️ the work you do on Spring (`core`, `boot`, `initialzr`, etc)! Keep up 💪🏾

**Comment by snicoll** [comment]
Sweet, thanks for the fast turnaround and the kind words!

Just to make sure I got this right, the `User-Agent` is something like `@nxrocks_nx-spring-boot/<version>`, e.g. `@nxrocks_nx-spring-boot/1.0.0`?

**Comment by tinesoft** [comment]
Yes exactly, as mentioned in the [guide](https://docs.spring.io/initializr/docs/current/reference/html/#metadata-format):

- `@nxrocks_nx-spring-boot` is the `clientId` (i chose to replace the `/` by `_`, to avoid issue with the version part)
- `x.y.z` is the `clientVersion`, and follows   the semantic versioning
