### ISSUE TITLE
[Bug] Do not configure Maven to build an executable jar when generating a library

### ISSUE THREAD

**Issue by tschaffter** [tinesoft/nxrocks#113]
### Plugin Name

@nxrocks/nx-spring-boot

### Plugin Version

4.1.0

### Nx Version

14.3.6

### Expected Behaviour

The app should successfully find and use a Spring Boot library generated with this plugin.

### Actual Behaviour

The `pom.xml` file generated by this plugin includes the following snippet:

```xml
<build>
  <plugins>
    <plugin>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-maven-plugin</artifactId>
    </plugin>
</build>
```

This snippet prevents the library from being consumed by an application that imports it. The error message would say that the package that the app is trying to import does not exist. For more detailed information about this error, see [this comment](https://github.com/tschaffter/nx-spring-boot-example/pull/2#issuecomment-1169322177).

The solution is given by this [Spring doc page](https://spring.io/guides/gs/multi-module/):

> To tell Maven to not build an executable jar for the Library project, you must remove the following block from the pom.xml created by the Spring Initializr:

```xml
<build>
  <plugins>
    <plugin>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-maven-plugin</artifactId>
    </plugin>
  </plugins>
</build>
```

### Steps to reproduce the behaviour

https://github.com/tschaffter/nx-spring-boot-example/pull/2#issuecomment-1169322177

**Comment by tschaffter** [comment]
Here is a screencast to illustrate the issue:

![Recording 2022-06-29 at 07 41 36](https://user-images.githubusercontent.com/3056480/176465339-883d62f9-51cf-4d49-b753-cffcb08b1e32.gif)

I'm using the version 4.1.0 of the plugin in [this repo](https://github.com/tschaffter/nx-spring-boot-example).

```console
$ yarn info @nxrocks/nx-spring-boot version
yarn info v1.22.19
4.1.0
Done in 1.25s.
```

**Comment by tinesoft** [comment]
Thanks for the confirmation @tschaffter .

This is indeed a bug (in maven-based library projects): the way the removal of the plugin might be flawn.


This should be quick to fix, stay tuned!
