### ISSUE TITLE
Use kebab-case for all targets offered by this plugin

### ISSUE THREAD

**Issue by tschaffter** [tinesoft/nxrocks#117]
### Is your feature request related to a problem? Please describe

No

### Describe the idea you'd like

The name of all the targets listed in the `project.json` generated by this Nx plugin should consistently use the same casing. Here are two example of targets that use different casing:

- `format-check` (kebab case)
- `buildImage` (lower camel case)

### Describe alternatives you've considered

From what I could see by glancing over the Nx website, they prefer kebab case target name. Alternatively, I couldn't find a target that used camel case.

### Additional context

Thanks!

**Comment by tinesoft** [comment]
Hi @tschaffter 

It makes sense. I will update

**Comment by tschaffter** [comment]
Thanks!
