### ISSUE TITLE
[Bug] Target `build` generated by `@nxrocks/nx-spring-boot:new` should cache the build artifacts

### ISSUE THREAD

**Issue by tschaffter** [tinesoft/nxrocks#126]
### Plugin Name

@nxrocks/nx-spring-boot

### Plugin Version

v4.1.0

### Nx Version

14.5.4

### Expected Behaviour

By default, the target `build` of a project is one of the target whose output artifacts are cached.

`nx.json`:

```json
  "tasksRunnerOptions": {
    "default": {
      "runner": "@nrwl/nx-cloud",
      "options": {
        "cacheableOperations": [
          "build",
          "test",
          "lint",
          "e2e"
        ],
        "canTrackAnalytics": false,
        "showUsageWarnings": true,
        "scan": true
      }
    }
  },
```

Below is the target `build` generated by the plugin:

```json
    "build": {
      "executor": "@nxrocks/nx-spring-boot:build",
      "options": {
        "root": "apps/plop"
      }
    },
```

The artifacts generated by this task when using Maven are saved to the folder `target`. Here is the content of the folder after building the app generated by the plugin:

![image](https://user-images.githubusercontent.com/3056480/184666503-4fad0ed9-82a3-47f7-9237-c357dff831f6.png)

If I empty the content of the folder `target` and run `nx build plop` again, then I would expect Nx to restore the content of the folder.

### Actual Behaviour

- Delete the content of the folder `target`.
- Build the app a second time but this time Nx does not run the task because it has been cached: `nx build plop`.
    ```console
     >  NX   Successfully ran target build for project plop (37ms)
 
       Nx read the output from the cache instead of running the command for 1 out of 1 tasks.
 
       See Nx Cloud run details at https://nx.app/runs/FrDt7oRlmf7
    ```

- The content of the folder `target` is still empty.

A solution is to let Nx know that the `folder` should be taken into account when creating the build cache.

```json
    "build": {
      "executor": "@nxrocks/nx-spring-boot:build",
      "options": {
        "root": "apps/plop"
      },
      "outputs": [
        "apps/plop/target"
      ]
    },
```

When using Gradle, the folder `build` should be cached instead.

### Steps to reproduce the behaviour

See above.

**Comment by tinesoft** [comment]
Hi Thomas!

Thanks for reporting this improvement, but I've already beaten you to it this time, ah ah  :-)

It was implemented in https://github.com/tinesoft/nxrocks/commit/45287156e1c85f29b27edb53d8fb14ad04a74ecc that will be released very soon ;-) 


Stay tuned!

**Comment by tschaffter** [comment]
Awesome, thanks!
