### ISSUE TITLE
[Bug] Unable to generate micronaut app without feature

### ISSUE THREAD

**Issue by JonathanGeoffroy** [tinesoft/nxrocks#134]
### Plugin Name

@nxrocks/nx-micronaut

### Plugin Version

1.0.2

### Nx Version

14.7.11

### Expected Behaviour

User should be able to create a micronaut application without feature

### Actual Behaviour

Generation crashes with a HTTP 400 error : 

```bash
 >  NX   ❌ Error downloading Micronaut project zip from 'https://launch.micronaut.io'

   If the problem persists, please open an issue at https://github.com/tinesoft/nxrocks/issues, with the following information:
   ------------------------------------------------------
   Download URL: https://launch.micronaut.io/create/default/com.example.test?javaVersion=JDK_8&lang=JAVA&build=MAVEN&test=JUNIT&features=
   Response status: 400
   Response headers: {}
   ------------------------------------------------------
   Pass --verbose to see the stacktrace.
```

This is probably due to the empty `feature` parameter as :

-  `https://launch.micronaut.io/create/default/com.example.test?javaVersion=JDK_8&lang=JAVA&build=MAVEN&test=JUNIT&features=` return a 400
- `https://launch.micronaut.io/create/default/com.example.test?javaVersion=JDK_8&lang=JAVA&build=MAVEN&test=JUNIT`  (please note the missing `feature` parameter) works fine

(Please also note Quarkus site seems to accept the empty `feature` parameter)

### Steps to reproduce the behaviour

1. Create a new app in a workspace
2. When CLI ask for features, just press Enter without adding any feature.
3. Wait for CLI to download generated zip.

**Comment by tinesoft** [comment]
Closed by #136
