### ISSUE TITLE
[Feature/suggestion] @nxrocks/nx-flutter:bootstrap -  link local packages

### ISSUE THREAD

**Issue by virginiarcruz** [tinesoft/nxrocks#140]
### Is your feature request related to a problem? Please describe

There's something on @nx-flutter, similar to `lerna bootstrap` for managing dependencies and linking local packages?
For example, the command would locally link packages via path dependency overrides without needing to edit **pubspec.yaml**.

Speaking of flutter, it would be something similar to what [Melos does](https://melos.invertase.dev/commands/bootstrap):
`melos bootstrap`

### Describe the idea you'd like

The suggestion would be a smarter way to manage dependencies instead of doing it manually.

**Comment by tinesoft** [comment]
Hi @virginiarcruz 

Thanks for using the plugin.

> There's something on @nx-flutter, similar to lerna bootstrap for managing dependencies and linking local packages?

No

> For example, the command would locally link packages via path dependency overrides without needing to edit **pubspec.yaml**.
> The suggestion would be a smarter way to manage dependencies instead of doing it manually.

What is the issue with editing the the **pubspec.yaml** manually to point to your local packages you need?
Also, with **Melos**,  how would you specify which local package another package in the workspace needs, without editing its **pubspec.yaml** ?

I don't know about **Melos**,  but from the look at it, it looks most of what it does can be done with Nx, thanks to its dependency graph. For example, you can run tasks like  `install` on dependency packages,  when running `build` on dependant packages in the workspace... (not done out-of the box by the plugin, but its simple to do)


Can you elaborate  more on what you need exactly?

**Comment by virginiarcruz** [comment]
Hey @tinesoft 

Thanks for answer :) 
> What is the issue with editing the the **pubspec.yaml** manually to point to your local packages you need? Also, with **Melos**, how would you specify which local package another package in the workspace needs, without editing its **pubspec.yaml** ?
> 

The issue of updating the **pubspec.yaml** manually is that for small projects it works. But for larger projects this can create an issue if, for example, you need to publish the packages (by git tag for example), you will need to update the version of each one manually in **pubspec.yaml**.
If the packages are coupled it will be necessary to manually check which versions should be updated. this can become a long and error-prone task.

> I don't know about **Melos**, but from the look at it, it looks most of what it does can be done with Nx, thanks to its dependency graph. For example, you can run tasks like `install` on dependency packages, when running `build` on dependant packages in the workspace... (not done out-of the box by the plugin, but its simple to do)
> 
> Can you elaborate more on what you need exactly?

The idea is to solve this issue by overriding local files which the Dart analyzer uses to read packages from without needing to update manually. 
Thus if a local package exists defined globally, and a different local package has it listed as a dependency, it will be linked regardless of whether a version has been specified.

The benefit is that all local packages in the repository can be interlinked to point to their local directories rather than 'remote' without **pubspec.yaml** modifications.

All this I'm considering the decision of publishing packages to avoid coupling.

**Comment by tinesoft** [comment]
Hi @virginiarcruz 

Thanks for elaborating.

Do I understand correctly :
* that in your workspace, you can link to packages that are globally installed on your machine without having them listed **explicitly** in the **pubspec.yaml** of related projects ?
* that *Melos** uses that feature to make your local packages available as global packages, and so, have them useable directly?


If so, what happen when you decide to build the dependant package? everything get bundled in ?

**Comment by virginiarcruz** [comment]
> * that in your workspace, you can link to packages that are globally installed on your machine without having them listed **explicitly** in the **pubspec.yaml** of related projects ?

No, packages can be published and I can link in pubspec.yaml.
But if I want to update the packages I don't do it manually, this is done by the command line and the dependencies are linked.

> * that _Melos_* uses that feature to make your local packages available as global packages, and so, have them useable directly?

Yes!
> 
> If so, what happen when you decide to build the dependant package (for distribution/publication)? everything get bundled in ?
> 
Yes, I can decide for example to use my package in the monorepo or make it available for other projects outside the monorepo.

**Comment by tinesoft** [comment]
Hi @virginiarcruz 

Thanks for the clarifications.

I still have a few questions, but overall I get the idea, and see the interest of `Melos`.

I will start implement something soon.
I might need additional information from you again, so if I can ping you by DM, it will be great.

Here is my twitter handler: @tinesoft.
Feel free to contact me there.

**Comment by maximveksler** [comment]
It's a welcomed feature, however I can't say it's the killer one (at least for me) on flutter projects. For me the killer is intellejent dependecy discovery, i.e. `affected` integation for monorepo based flutter sturctued containing several apps.

**Comment by tinesoft** [comment]
@virginiarcruz I very proud to announce the support for melos, via my newest plugin: @nxrocks/nx-melos !

Instruction and usage can be found here: https://github.com/tinesoft/nxrocks/tree/develop/packages/nx-melos

This plugin can be installed  in addition to nx-flutter plugin that it completes.

Please give it a try, and let me know how it works for you!

**Comment by virginiarcruz** [comment]
Hey @tinesoft 
Thank you for the update.
I'll test and give feedback there. 💯

**Comment by tinesoft** [comment]
Hi @virginiarcruz 

did you get a chance to play with the new `nx-melos` plugin yet?
