### ISSUE TITLE
[Feature] @nxrocks/nx-flutter:flutter-shared-widget-across multiple project

### ISSUE THREAD

**Issue by SOG-web** [tinesoft/nxrocks#147]
### Describe the idea you'd like

I don't how possible it is to have shared widget like a library, component just like the way nx-expo does it
example: Run `nx g @nxrocks/nx-flutter:component component-name --project=app-name` to generate a new component.
Run `nx g @nxrocks/nx-flutter:lib my-lib` to generate a library.

### Describe alternatives you've considered

nx-expo

**Comment by SOG-web** [comment]
Hi, I have been able to generate the shareable modules, but how do i use it in another flutter project

**Comment by tinesoft** [comment]
Hi @SOG-web 

Sorry for the late answer.

> Hi, I have been able to generate the shareable modules, but how do i use it in another flutter project

You simply have to reference it in the `pubspec.yaml` file of the target project, as such:
```yaml
dependencies:
  flutter:
    sdk: flutter

  my-lib:
    path: '../../libs/my-lib'
```

A good tutorial can be found here: https://developer.school/tutorials/create-flutter-apps-using-nx-workspaces
