### ISSUE TITLE
[Bug] Error downloading Spring Boot project zip

### ISSUE THREAD

**Issue by OsvaldoBFGO** [tinesoft/nxrocks#149]
### Plugin Name

@nxrocks/nx-spring-boot

### Plugin Version

v ^6.0.0

### Nx Version

15.2.1

### Expected Behaviour

Expected to create springboot project

### Actual Behaviour

Error while dowlading project, with this message:

   Download URL: https://start.spring.io/starter.zip?type=maven-project&language=java&name=si-vale-fintech-api&groupId=com.upsv&artifactId=fintech&packageName=com.upsv.fintech&javaVersion=11&packaging=jar&dependencies=4.0.0&description=API&bootVersion=2.4.1
   Response status: 400
   Response headers: {}

### Steps to reproduce the behaviour

Using de the nx console puglin in vs code, and filling out the generation. Using this commnad nx generate @nxrocks/nx-spring-boot:project

**Comment by OsvaldoBFGO** [comment]
npx nx generate @nxrocks/nx-spring-boot:project si-vale-fintech-api --dependencies=4.0.0 --description='API para App y Portal de Fintech Up Si Vale' --directory=packages --artifactId=fintech --bootVersion=2.4.1 --groupId=com.upsv --packageName=com.upsv.fintech --no-interactive --dry-run

This is the full commnad line

**Comment by tinesoft** [comment]
Hi @OsvaldoBFGO 

Thanks for using the plugin. 
The error you are having seems to be due to a bad value for the "**dependencies**" parameter. You set "4.0.0",  while it should be a list of  [id of the dependencies](https://start.spring.io/dependencies) you want to  include in the project (for example "webflux,devtools,data-jpa").

**Comment by tinesoft** [comment]
Should be fixed by https://github.com/tinesoft/nxrocks/releases/tag/nx-spring-boot%2Fv6.1.0
