### ISSUE TITLE
[Bug] Many warnnings are reported when installing nx-flutter

### ISSUE THREAD

**Issue by maximveksler** [tinesoft/nxrocks#153]
### Plugin Name

@nxrocks/nx-spring-boot

### Plugin Version

@nxrocks/nx-flutter@5.0.0

### Nx Version

6.14.17

### Expected Behaviour

Install and runs clearnly.

### Actual Behaviour

Warnning such as 

```
npm WARN @nxrocks/common@2.0.0 requires a peer of yargs@17.6.0 but none is installed. You must install peer dependencies yourself.
```

See gist for full list https://gist.github.com/maximveksler/949dfbcd682a93fe6172312eee4576bf

### Steps to reproduce the behaviour

Reproduction log is too long, please see gist https://gist.github.com/maximveksler/377053d9fd60663f743a9b94a570a85f

**Comment by tinesoft** [comment]
Should be fixed by https://github.com/tinesoft/nxrocks/releases/tag/nx-flutter%2Fv5.1.0
