### ISSUE TITLE
[Bug] ./gradlew not found - multi-module Gradle project

### ISSUE THREAD

**Issue by mklueh** [tinesoft/nxrocks#156]
### Plugin Name

@nxrocks/nx-quarkus

### Plugin Version

4.1.0

### Nx Version

15.4.1

### Expected Behaviour

I'm trying to transition my multi-module Gradle project into an Nx workspace. 

I currently have one gradlew binary at the root of the project, but as soon as I run one of the projects within the workspace via Nx, it looks for the executable within the application folder, not the root of the project.

Is it somehow possible to tell this plugin to look for Gradle in the project's root instead?

### Actual Behaviour

```
Executing command: ./gradlew quarkusDev 
/bin/sh: 1: ./gradlew: not found
Failed to execute command: ./gradlew quarkusDev 
Error: Command failed: ./gradlew quarkusDev 
    at checkExecSyncError (node:child_process:861:11)
    at execSync (node:child_process:932:15)
    at runBuilderCommand (/home/user/workspace/nx-nuxt-3-gradle-quarkus/node_modules/@nxrocks/common/src/lib/core/jvm/utils.js:20:38)
    at runQuarkusPluginCommand (/home/user/workspace/nx-nuxt-3-gradle-quarkus/node_modules/@nxrocks/nx-quarkus/src/utils/quarkus-utils.js:14:43)
    at /home/user/workspace/nx-nuxt-3-gradle-quarkus/node_modules/@nxrocks/nx-quarkus/src/executors/dev/executor.js:10:60
    at Generator.next (<anonymous>)
    at /home/user/workspace/nx-nuxt-3-gradle-quarkus/node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>)

```

### Steps to reproduce the behaviour

1. Add Quarkus app to apps of Nx workspace
2. Pull out settings.gradle into root and all Gradle binaries + the wrapper directory
3. Create the build.gradle in root
```
plugins {
	id 'java'
    id 'io.quarkus'
	id 'maven-publish'
}




subprojects {

    apply plugin: 'java'
    apply plugin: 'idea'

    repositories {
        mavenCentral()
        mavenLocal()
    }

    dependencies {
        implementation enforcedPlatform("${quarkusPlatformGroupId}:${quarkusPlatformArtifactId}:${quarkusPlatformVersion}")
        implementation 'io.quarkus:quarkus-arc'
        implementation 'io.quarkus:quarkus-resteasy-reactive'
        testImplementation 'io.quarkus:quarkus-junit5'
        testImplementation 'io.rest-assured:rest-assured'
    }

}

group 'com.example'
version '1.0.0-SNAPSHOT'

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

test {
    systemProperty "java.util.logging.manager", "org.jboss.logmanager.LogManager"
}
compileJava {
    options.encoding = 'UTF-8'
    options.compilerArgs << '-parameters'
}

compileTestJava {
    options.encoding = 'UTF-8'
}

publishing {
	publications {
		mavenJava(MavenPublication) {
			artifact jar
		}
	}
}
tasks.withType(GenerateModuleMetadata).configureEach {
	suppressedValidationErrors.add('enforced-platform')
}

```
5. Add the application as an include in settings.gradle
```
pluginManagement {
    repositories {
        mavenCentral()
        gradlePluginPortal()
        mavenLocal()
    }
    plugins {
        id "${quarkusPluginId}" version "${quarkusPluginVersion}"
    }
}


include ":apps:app-name"

rootProject.name='root-project-name'

```

**Comment by tinesoft** [comment]
Hi @mklueh 
Thanks for using the plugin and for opening an issue.

What you described is rather a feature than a bug.

The philosophy of this plugin is to be **as close as** possible to what is generated by the official [Quarkus code generator](https://code.quarkus.io) (that the plugin uses behind the scenes) , and right now,  it does not support multi-module projects either.

Also, all build commands **are run in the context of a specific project** (application or library) in the Nx workspace,
which means that we use the `build.gradle` within that project and cannot rely on one globally available at root level (not standard).

That being said,  I will continue thinking about a way to achieve that right in the plugin, for both Gradle and Maven build systems

**Comment by mklueh** [comment]
@tinesoft thanks for clarifying.

I currently solved it by just doing

```
"targets": {
    "build": {
      "executor": "nx:run-commands",
      "cwd": "/",
      "options": {
        "command": "./gradlew :apps:first-app:first-app-server:build"
      }
    }
  },
```

Which is a bit redundant if you have to define one new target for each Gradle command and project
