### ISSUE TITLE
[Bug] Maven commands failed locally because of invalid target release

### ISSUE THREAD

**Issue by kkhanhluu** [tinesoft/nxrocks#157]
### Plugin Name

@nxrocks/nx-spring-boot

### Plugin Version

6.2.1

### Nx Version

15.5.0

### Expected Behaviour

./mvnw commands should successfully completes on first execution.

### Actual Behaviour

The nx commands fail because of invalid target release, after I generate new application locally by the plugin
```
nx run <your-boot-app>:run
```
Here is an example of the error

![Screen Shot 2023-01-16 at 03 12 36](https://user-images.githubusercontent.com/38130967/212584690-632bc700-b470-4177-824d-0cb605c1d690.jpeg)

### Steps to reproduce the behaviour

1. Fork this repo: [https://github.com/kkhanhluu/e-shop]https://github.com/kkhanhluu/e-shop)
2. Run the command `nx run product-service:run`

**Comment by tinesoft** [comment]
Hi @kkhanhluu 

Thanks for using the plugin.
From the error logs, it seems that **you dont have Java 17 or later installed on your machine...**
This is required to compile your boot app (see in [pom.xml](https://github.com/kkhanhluu/e-shop/blob/0900862ee397ddd90e65f574560f35de83adf748/apps/product-service/pom.xml#L17)
Can you confirm, by running `java --version` please?

**Comment by kkhanhluu** [comment]
Hi @tinesoft,

Thanks for your quick reply. I stupidly forgot to set `java-version` for my project. Everything works fine now. Thanks again for your support!
