### ISSUE TITLE
[Bug] Connection over Proxy not using correct protocol

### ISSUE THREAD

**Issue by Darkterror45** [tinesoft/nxrocks#158]
### Plugin Name

@nxrocks/nx-spring-boot

### Plugin Version

6.3.0

### Nx Version

15.5.2

### Expected Behaviour

The proxy agent returned should be based on the protocol based on the URL and not on the Proxy. See also 
![image](https://user-images.githubusercontent.com/22987448/224945480-65f2ea20-7936-427e-9dfe-3366a0a93469.png)

It seems that the Http(s)ProxyAgent needs to based on the Server URL and not on the Proxy URL.

I can also create an PR for this if you want ?

### Actual Behaviour

Currently it is trying to connect with the false protocol if the procotol from the proxy and server are not the same.

Here a short matrix based on the above image:
| Proxy | Server | Status      |
|-------|--------|-------------|
| HTTP  | HTTP   | working     |
| HTTPS | HTTP   | not working |
| HTTP  | HTTPS  | not working |
| HTTPS | HTTPS  | working     |

### Steps to reproduce the behaviour

1. Have a setup with a http proxy.
2. Generate a app which needs an connection.

**Comment by tinesoft** [comment]
Hi @Darkterror45 

Thanks for using the plugin and for reporting this.

Please, feel free to submit the PR, I'll gladly review and accept it ^^.
FYI: The code affecting the HTTP Proxy was recently changed in this [commit](a55d3b7f1cc70de83b103c0c4687ac9c21f1c15e) 


Just make sure to follow the [contributing guidelines](https://github.com/tinesoft/nxrocks/blob/develop/.github/CONTRIBUTING.md)
