### ISSUE TITLE
[Bug] Flutter plugin using NX console some executors don't work as expected including the run command

### ISSUE THREAD

**Issue by algoflows** [tinesoft/nxrocks#160]
### Plugin Name

@nxrocks/nx-flutter

### Plugin Version

latest

### Nx Version

latest

### Expected Behaviour

NX Console some of the executors don't work

- Assemble errors out and doesn't complete
![Screenshot 2023-03-18 at 19 22 10](https://user-images.githubusercontent.com/65465380/226132640-eecf03cd-b8f3-4edb-866e-f7e6cdf2cd0b.png)

- Run doesn't work when executing using the vscode console UI
- Seems to be missing the the :run off the end of the command executed
![Screenshot 2023-03-18 at 19 24 39](https://user-images.githubusercontent.com/65465380/226132750-0db0579c-5bbe-436d-aba8-7630934e5df1.png)
![Screenshot 2023-03-18 at 19 23 33](https://user-images.githubusercontent.com/65465380/226132695-42a0dd9f-fa7d-458a-bd56-85b31e5b9f26.png)

### Actual Behaviour

All executor commands should execute and run when using the NX Console UI

### Steps to reproduce the behaviour

- Install NX on a fresh project and generate a blank project.
- Then try to use the run command

**Comment by tinesoft** [comment]
Fixed in Nx console (see related ticket above)
