### ISSUE TITLE
[Bug] Namespace changed in Nx v16

### ISSUE THREAD

**Issue by LexanRed** [tinesoft/nxrocks#167]
### Plugin Name

@nxrocks/nx-spring-boot

### Plugin Version

7.0.0

### Nx Version

16.0.1

### Expected Behaviour

Run nx-spring-boot commands to execute maven goals.

### Actual Behaviour

Every command fails with the following error: 
` Cannot find module '@nrwl/workspace/src/utils/fileutils'`

### Steps to reproduce the behaviour

1. Install a fresh Nx v16 workspace
2. Add @nxrocks/nx-spring-boot
3. Create a spring boot application (that worked)
4. Try to build the application using nx (nx mySpringApp:build)

Error occurs on every command. (Build, test, build-image, ...)

Should be an easy fix. In v16 the namespace changed. 
I could fix it locally by changing @nxrocks/common/src/lib/core/jvm/utils.js line 6

From: `const fileutils_1 = require("@nrwl/workspace/src/utils/fileutils");`
To: `const fileutils_1 = require("@nx/workspace/src/utils/fileutils");`

**Comment by tinesoft** [comment]
Closed in https://github.com/tinesoft/nxrocks/releases/tag/nx-spring-boot%2Fv8.0.0
