### ISSUE TITLE
[Bug] User options are not used to generate the project

### ISSUE THREAD

**Issue by Kwandes** [tinesoft/nxrocks#17]
Plugin Version:
- nx-spring-boot@1.2.0

Nx Version (`nx --version`):
- 11.0.20

Angular CLI version (`ng --version`):
- 11.0.4

Node version:
- 14.15.1

Operating System:
- Windows 10 Pro, version 20H2

#### Expected Behaviour

When creating a Java Spring app in an empty NX monorepo, the user is prompted to select various project settings.
Upon selection, those settings should apply and generate the project properly.

#### Actual Behaviour
The generated project does not have some of the values applied, and the defaults seem to be applied instead:
- GroupId input: `dev.hotdeals`. Pom.xml: ´com.example´
- ArtifactId input: `api`, name when creating the project: `java-api`. Pom.xml name: `demo`
- Project Description input: `` (nothing, just pressed enter). Expected empty description, instead got the default description of `Demo Project for Spring Boot` 
- Main class name was DemoApplication instead of ApiApplication, due to the name being incorrectly applied. Same applies to the default application test
- Project type input: `maven`. The project becomes a maven project but the nx commands seem to sue gradle (possibly a different issue). Specifically, when running `nx run java-api:run`, the output is
```
> nx run java-api:run
Executing command: ./gradlew.cmd bootRun
'.' is not recognized as an internal or external command,
operable program or batch file.
Failed to execute command: ./gradlew.cmd bootRun
```

This result of the command can be seen in my [repository](https://github.com/Kwandes/app-sandbox/commit/4670c9f73e7ee0e5bdd7abb197d1e704b3091133) and [this commit](https://github.com/Kwandes/app-sandbox/commit/71da9f5527809ae88a1ce7a19c6c06d46eb4b277)\
[Next commit](https://github.com/Kwandes/app-sandbox/commit/e9e3b5bdb975c8cfdd50c1cb386ae4ae808723a9) shows me fixing some of the invalid information (does not fix the gradle-instead-of-maven issue)

#### Workspace setup
Create a new workspace in the root folder of the repository
`npx create-nx-workspace@latest app-sandbox`

#### Java Project setup
*[guide](https://www.linkedin.com/pulse/integrating-spring-boot-application-inside-nx-workspace-tine-kondo/)* \
Navigate into the NX workspace directory `cd app-sandbox` \
Install a dependancy for Java and Spring 
`npm install @nxrocks/nx-spring-boot --save-dev`

Generate a Java app
`nx g @nxrocks/nx-spring-boot:app java-api` \
Project type: maven
Packaging: jar
Java version: 11
GroupId: dev.hotdeals
ArtifactId: api
Package name: dev.hotdeals.api
About:
Dependencies:

**Full output of a completed generation command**
```
? Which type of project would you like to generate? Maven Project
? Which packaging would you like to use? Jar
? Which version of Java would you like to use? 11
? Which language would you like to use? Java
? What groupId would you like to use? dev.hotdeals
? What artifactId would you like to use? api
? What package name would you like to use? dev.hotdeals.api
? What is the project about?
? What dependencies would you like to use (comma separated)?
        > Go to https://start.spring.io/dependencies to get the ids needed here
    Downloading Spring Boot project zip from : https://start.spring.io/starter.zip?type=maven-project&language=java&groupdId=dev.hotdeals&artifactId=api&packageName=dev.hotdeals.api&javaVersion=11&packaging=jar...
    Extracting Spring Boot project zip to : apps/java-api...
UPDATE workspace.json (1211 bytes)
UPDATE nx.json (780 bytes)
```

**Comment by tinesoft** [comment]
Hi @Kwandes 

Thanks for using the plugin, and for reporting the issue.

I was not about to reproduce the bug you mentioned when running the app (`gradle` being used instead of `maven`). Also, when you leave the`"description"`field empty, `Spring Initialzr` automatically uses the default description (`"Demo Project for Spring Boot"`), so there is nothing I can do here.

For the rest, custom `groupId`, `name` are now applied properly to generate the code.
