### ISSUE TITLE
[Bug] - Nx graph fails when having a flutter app and a flutter lib 

### ISSUE THREAD

**Issue by DatStorm** [tinesoft/nxrocks#170]
### Plugin Name

@nxrocks/nx-flutter

### Nx Report

 >  NX   Report complete - copy this into the issue template

   Node   : 19.9.0
   OS     : win32 x64
   pnpm   : 8.4.0
   Hasher : Native

   nx             : 16.1.1
   @nx/workspace  : 16.1.1
   @nx/devkit     : 16.1.1
   @nrwl/tao      : 16.1.1
   ---------------------------------------
   Community plugins:
   @nxrocks/nx-flutter : 7.0.2

### Expected Behaviour

NX graph should be started as normally. 

### Actual Behaviour

![image](https://user-images.githubusercontent.com/23613201/236680386-9b4f7427-6a9f-4494-b2ff-49143f268813.png)
Failing to run the graph when app is dependent on the lib. 

### Steps to reproduce the behaviour

1. Follow this guide: https://developer.school/tutorials/create-flutter-apps-using-nx-workspaces 
2. Create the app and run the graph (works)
3. Create the lib and use it in the flutter app.
4. Try to run the nx graph. 
5. See that it fails as shown on the image above.

**Comment by DatStorm** [comment]
Can create a sample repo if not able to reproduce.

**Comment by tinesoft** [comment]
Hi @DatStorm 

Thanks for using the plugin and for reporting this.
I will start investigating. In the meantime, if you can provide a repro project that will be very useful, it will help speed up investigations.

**Comment by DatStorm** [comment]
Hey 

Thanks for the quick reply. 

You can fork it here: https://github.com/DatStorm/nx-bug-nxrocks

**Comment by tinesoft** [comment]
Ok,

first observation, it seems the issue is specific to windows. I tried running the `nx graph` command on the repo you provided, and it worked just fine...
<img width="1526" alt="image" src="https://user-images.githubusercontent.com/4053092/236692498-5a078f66-f0f0-475b-b269-fb749a5ec823.png">

**Comment by DatStorm** [comment]
Yeah I see. Any idea what is causing the problem on windows?

**Comment by tinesoft** [comment]
No, not just at looking at the code unfortunately... I need to debug while on a windows machine

I will try again once I get my hands on such machine, probably tomorrow
