### ISSUE TITLE
Adopting Nx to SpringBoot MonoRepo's

### ISSUE THREAD

**Issue by AnilReddy231** [tinesoft/nxrocks#175]
Hello There,

I am pretty new to Nx. we have spring-boot APIs in a Mono repo. we would like to adopt Nx for it. I had gone through several readme's documentations Nx, and learned that it needs package.json. All the new projects we could generate with Nx coming with package.json. But when it comes to our mono-repo, we have pom.xml alone. I am not finding much of guidelines on migrating spring-boot mono-repos to Nx or adding Nx. Can you please provide some guidance on that?

**Comment by tinesoft** [comment]
Hi @AnilReddy231 

Sorry for the delay in responding, and thanks for using the plugin.

Indeed, Nx, which is based on NodeJS, requires a `package.json` to install all the runtimes dependencies it needs.

If you don't want to  have a `package.json` or a `node_modules/` alongside with it, you can

 1- init your workspace with this command:

 `npx nx init --useDotNxInstallation`

It will create a Nx workspace that come with [Nx Wrapper](https://nx.dev/concepts/more-concepts/nx-and-the-wrapper).
Just like Maven Wrapper (mvnw) or Gradle Wrapper (gradlew), that wrapper is responsible of managing Nx installation automatically, so you dont have to worry about it, and you will have a minimal presence of Nx required files in your workspace.

The only file that would be relevant in the workspace is the `nx.json`: Nx configuration file.

2- add the `@nxrocks/nx-spring-boot` to the workspace's `nx.json`:

Edit the `"installation.plugins"` section,  and add `"@nxrocks/nx-spring-boot": "<version>"`

3- Then, you can simply run `./nx @nxrocks/nx-spring-boot:new <projectName>` to add new Spring Boot projects within the workspace.


I have just created a new CLI package  called `create-nx-spring-boot`  that will automate all the steps above for you!

It will be released next week.
