### ISSUE TITLE
Run arguments on project level are not pass to ./mvnw spring-boot:run only the ones that are coded to the project.json

### ISSUE THREAD

**Issue by SchwarzAmihay** [tinesoft/nxrocks#176]
### Plugin Name

@nxrocks/nx-spring-boot

### Nx Report

We want to run the spring-boot app with a different argument each time, Passing the argument on the project-level run dialog  (red circle) does not have any effect, only the hard-codded args in the project.json (green circle) are passed to the `./mvnw spring-boot:run`

![image](https://github.com/tinesoft/nxrocks/assets/131960634/1637b8fc-a8f1-4eee-a02c-8ef171309c47)

### Expected Behaviour

both arguments should be pass

### Actual Behaviour

only the hard-codded args are passed  to `./mvnw spring-boot:run`

### Steps to reproduce the behaviour

1. create a spring-boot application
2. right click on the project run executor on the Nx console 
3. edit the run configuration
4. run

**Comment by tinesoft** [comment]
Hi @SchwarzAmihay 

First of all, I apologised for the (very) late answer... somehow it got off my radar and I didn't noticed it until now.

Could you try wrapping your options into `--args="<YOUR OPTIONS HERE>"`, which is the expected format to send additional args to the executor.

**Comment by SchwarzAmihay** [comment]
Hi @tinesoft, thank you for getting back.
I did as you suggested and still it didn't work

**Comment by tinesoft** [comment]
Humm 🤔

Can you try running the same task directly, via a command line:

```
npx nx run back-ends-insights:run --args="<Your Options Here>"
```


Also, I'm not familiar with  "Edit Run/Debug configuration" dialog you showcased in your first post...

- Where is it coming from? 
- I suppose you are using Intellij IDEA? Which version ? 
- Are you using a custom **Nx Console** plugin too or the official one (from @nrwl)?

**Comment by SchwarzAmihay** [comment]
Thank you @tinesoft .
I am using the webstorm with the official plugin https://plugins.jetbrains.com/plugin/21060-nx-console.

It appears that adding `--args="-Dspring-boot.run.jvmArguments='........'"` solves the problem, there is another problem that commas `,` are not excepted inside but after replacing it with `;` it all works.

You can go ahead and close this issue, 
Thank you

**Comment by tinesoft** [comment]
I'm glad I could help!

Don't hesitate to ⭐ the project, it helps me too ;-)
