### ISSUE TITLE
[Bug] [nx-flutter] Schematic "application" cannot resolve the factory.

### ISSUE THREAD

**Issue by benoitskipr** [tinesoft/nxrocks#21]
Plugin Name and Version:
nx-flutter@1.0.0

Nx Version (`nx --version`):
11.0.20

Angular CLI version (`ng --version`):
11.0.6

#### Expected Behaviour
the application should be created

#### Actual Behaviour
tool ends with `Schematic "application" cannot resolve the factory.`

#### Steps to reproduce the behaviour
`nx g @nxrocks/nx-flutter:app dora`

? What package name would you like to use? `dora`
? What is the project about? `Maas Web for Dora`
? Which Android language would you like to use? `Kotlin`
? Which iOS language would you like to use? `Swift`
? Which type of Flutter project would you like to create? `Flutter application`
? Which platforms would you like to use (--template must have been set to 'app' or 'plugin') ? `Web platform`

thanks for this tool

**Comment by tinesoft** [comment]
Hi @benoitskipr 

Thank you for using the plugin and for reporting the issue!

There was indeed an error with the published package on NPM(`@nxrocks/nx-flutter@1.0.0`: the *.ts file were not compiled properly, thus considered missing when running the `application` Schematic)

I am working on a fix as we speak.  Stay tuned.

**Comment by tinesoft** [comment]
I've just published a new version (v1.1.0) that should fix the issue.
