### ISSUE TITLE
[Bug] NX command with Maven not executing for some reason, gradle seems to be working

### ISSUE THREAD

**Issue by Divaaaaaan** [tinesoft/nxrocks#228]
### Plugin Name

@nxrocks/nx-spring-boot

### Nx Report

Node   : 20.12.2
OS     : linux-x64
pnpm   : 9.0.6

nx             : 19.4.2
@nx/js         : 19.4.2
@nx/workspace  : 19.4.2
@nx/devkit     : 19.4.2
@nrwl/tao      : 19.4.2
typescript     : 5.5.3
---------------------------------------
Registered Plugins:
@nxrocks/nx-spring-boot
---------------------------------------
Community plugins:
@nxrocks/nx-spring-boot : 10.2.1

### Expected Behaviour

Execute any command, server, build, format etc to run as expected or as normal

### Actual Behaviour

![image](https://github.com/tinesoft/nxrocks/assets/139715076/e55c0cd3-dbe8-4c11-ad66-69680d037595)
The command just hangs, nothing is executed. 

### Steps to reproduce the behaviour

1. Create maven project
2. Add any spring boot dependancies/none
3. Run desired nx command

**Comment by tinesoft** [comment]
Hi @Divaaaaaan 

Thanks for using the plugin.

Can you elaborate about the issue you are having? provide the error stacktrace  and the exact reproduction steps;

So far, I was NOT abble to reproduce the errror when creating a spring boot app with the latest v10.2.1...

**Comment by tinesoft** [comment]
Never mind,  I misread your original post. Indeed I can see/reproduce the issue now.

Will try to provide a fix.

Stay tuned!

**Comment by Divaaaaaan** [comment]
Hi @tinesoft 

Awesome thanks, I did try checking the package itself but was unable to find anything so I just ended up using the standard mvn commands for now.

**Comment by tinesoft** [comment]
No worries, I have identified the issue :-) 
The fix is in progress. It should be released very shortly
