### ISSUE TITLE
[Bug] [nx-flutter] missing quotes around -description value

### ISSUE THREAD

**Issue by benoitskipr** [tinesoft/nxrocks#23]
Plugin Name and Version:
nx-flutter 1.2.0

Nx Version (`nx --version`):
11.1.2

Angular CLI version (`ng --version`):
11.0.6

#### Expected Behaviour
I should be able to write multiple words for the Description step

#### Actual Behaviour
command line fails because of the space in description
```Failed to execute command: flutter create --project-name=design --org=skipr.design --description=Design Demo --android-language=kotlin --template=app --platforms=web apps/design```

#### Steps to reproduce the behaviour
`npx @angular-devkit/schematics-cli @nxrocks/nx-flutter:app design`
> ? What is the project about? Design Demo

**Comment by tinesoft** [comment]
Hi @benoitskipr 


Thanks for reporting the issue!
I now automatically quote the description if needed, to avoid the error.
The fix will be released very soon.


Cheers

**Comment by benoitskipr** [comment]
thanks!
