### ISSUE TITLE
[Bug] Maven wrapper not found in sub directory

### ISSUE THREAD

**Issue by Divaaaaaan** [tinesoft/nxrocks#230]
### Plugin Name

@nxrocks/nx-spring-boot

### Nx Report

![image](https://github.com/user-attachments/assets/d4f3c0b4-afe4-4360-bf64-648b78bd3c8f)

### Expected Behaviour

Able to run the standard commands, format, serve etc. from the root.

### Actual Behaviour

![image](https://github.com/user-attachments/assets/68a1ed7a-5347-4008-a83e-2c2f51aa4d07)

### Steps to reproduce the behaviour

1. Create new NXRocks Spring Boot app
2. Select Maven project
3. Try run any of the commands

**Comment by tinesoft** [comment]
Hi,

Thanks for reporting the issue.
Can you show me the files/folders in your workspace? And options did you choose when generating the project?

**Comment by tinesoft** [comment]
Should be fixed now: https://github.com/tinesoft/nxrocks/releases/tag/nx-spring-boot%2Fv10.2.3

**Comment by Divaaaaaan** [comment]
@tinesoft Awesome, just updated and working! Thanks for the quick fix, apologies for not replying earlier. Was bed time xD
