### ISSUE TITLE
[Bug] Project setup not working as expected

### ISSUE THREAD

**Issue by networkinss** [tinesoft/nxrocks#231]
### Plugin Name

@nxrocks/nx-spring-boot

### Nx Report

Node           : 18.18.2
OS             : linux-x64
Native Target  : x86_64-linux
pnpm           : 8.10.5

nx (global)        : 19.3.0
nx                 : 19.5.6
@nx/js             : 19.5.6
@nx/jest           : 19.5.6
@nx/eslint         : 19.5.6
@nx/workspace      : 19.5.6
@nx/cypress        : 19.5.6
@nx/devkit         : 19.5.6
@nx/eslint-plugin  : 19.5.6
@nx/playwright     : 19.5.6
@nx/react          : 19.5.6
@nx/vite           : 19.5.6
@nx/web            : 19.5.6
typescript         : 5.5.4
---------------------------------------
Registered Plugins:
@nx/vite/plugin
@nx/eslint/plugin
@nx/playwright/plugin
@nx/jest/plugin
@nxrocks/nx-spring-boot
---------------------------------------
Community plugins:
@nxrocks/nx-spring-boot : 10.0.2

### Expected Behaviour

nx install springservice 
nx install springlib
should build the project.

### Actual Behaviour

Running the commands 
nx install springlib 
nx install springservice 
seems not to do something. Looks like an infinite loop.
Adding --verbose=true does not show something useful.
I would expect it to do either the build or show an error message what is wrong.

I am quite not sure, what the issue is, if I made a wrong setup, something is missing or if there is a bug.
However, if it is not a bug, I would expect an error message to come up with a hint what is wrong.
I made a simple sample project to reproduce the issue:
https://github.com/networkinss/nxsamplespring

### Steps to reproduce the behaviour

It is also described in the README.md of the github project:
https://github.com/networkinss/nxsamplespring

1. Create React monorepo.
2. Add @nxrocks/nx-spring-boot.
3. Create app springservice in apps.
4. Create library springlib in libs.
5. Link springlib to springservice.

pnpx create-nx-workspace@latest nxsample --preset=react-monorepo
pnpm install @nxrocks/nx-spring-boot --save-dev nx g @nxrocks/nx-spring-boot:project springservice
nx g @nxrocks/nx-spring-boot:project springlib --directory libs
nx show projects
nx dep-graph
nx g @nxrocks/nx-spring-boot:link --sourceProjectName springlib --targetProjectName springservice

**Comment by tinesoft** [comment]
Hi @networkinss 

Thanks for using the plugin. However, it seems you are not using the `link` option right: it is meant to **implicitly link** a spring-boot (**backend**) project within the workspace, with one or many related **frontend** projects related to it.

You don't need to create such **implicit link** between your `springservice ` app and your `springlib` lib (your "Step 5").
Simply add a dependency of the latter in the `pom.xml` or the `build.gradle[.kts]` of the first, and the plugin will automatically create an **explicit link** between the 2 projects  (backend-related) for you.

Then, you no longer need to manually run `nx install springlib`: it will be done automatically when you run `nx build springservice` or `nx install springservice`

Try and  let me know if your issue persists

**Comment by networkinss** [comment]
Thanks for helping.
I removed the implicit dependecy from the project.json in springservice and added a maven dependency in the pom.xml.
However, trying with 
`nx install springservice --verbose=true`
it seems to do nothing.
It looks like a more general problem.

**Comment by tinesoft** [comment]
Can you please 

- share the output of `nx install springservice --verbose` 
- share the output of `nx graph`
- share the content of your `pom.xml` and `project.json`  files 

so that I understand your workspace better

**Comment by networkinss** [comment]
nx install springservice --verbose=true:
Verbose does not help much...
The output is:

> amrit@mini:nxsamplespring_0$ nx install springservice --verbose=true
> 
>  NX   Running target install for project springservice and 1 task it depends on:
> 
> 

It stays like that forever, waited already up to 10-15 min. 
Looks much like an infinite loop.

pom.xml and project.json files:
The project is there completely at 
[https://github.com/networkinss/nxsamplespring] 

Attached the screenshot for nx graph:
![Bildschirmfoto zu 2024-08-02 11-52-27](https://github.com/user-attachments/assets/cdb5d111-1d17-42ad-831d-ea291e33f1b2)
Very basic and simple :).

**Comment by merlinofcha0s** [comment]
Same issue here, it stays stuck forever.

<img width="383" alt="圖片" src="https://github.com/user-attachments/assets/8ee41b01-238f-490a-843b-9da964759b7e">

**Comment by tinesoft** [comment]
Hi folks,

Thanks for reporting this and for the repro project. I'll have a deeper look and let you know
Stay tuned

**Comment by tinesoft** [comment]
Ok, 
I just noticed you are using an old version of the plugin (`v10.0.2`).
That issue was already fixed in more recent verison , please update to https://github.com/tinesoft/nxrocks/releases/tag/nx-spring-boot%2Fv10.2.3 (latest version to date)

**Comment by networkinss** [comment]
I did not specify a version, it is taking the latest from npm.
I looked at npmjs.com and the version with tag "latest" is that version: 10.0.2.
So that is the bug, it does not point to the real latest version 10.2.3.

**Comment by tinesoft** [comment]
Hi @networkinss 

> I did not specify a version, it is taking the latest from npm.
>I looked at npmjs.com and the version with tag "latest" is that version: 10.0.2.
> So that is the bug, it does not point to the real latest version 10.2.3.

Whoa, good catch! 

It is indeed a bug in the release flow I was not aware of...
 I will update the pointer of "latest" tag (hopefully tonight), once I have access to my dev machine.

Thanks again for reporting this

**Comment by tinesoft** [comment]
OK, the incorrect version issue has been fixed 

<img width="1299" alt="image" src="https://github.com/user-attachments/assets/2e4e1d9d-3add-4ba8-a73a-015d5e1c87c9">

**Comment by merlinofcha0s** [comment]
Thanks a lot, guys !
