### ISSUE TITLE
[Bug] Failed to process the project graph with "@nxrocks/nx-flutter". Source file "..." does not exist in the workspace.

### ISSUE THREAD

**Issue by jochemvanweelde** [tinesoft/nxrocks#232]
### Plugin Name

@nxrocks/nx-flutter

## When running with local dependencies listed in pubspec
```
>  NX   Failed to process the project graph with "@nxrocks/nx-flutter".

   Source file "flutter-graphql-client" does not exist in the workspace.
```
```
Error: Failed to process the project graph with "@nxrocks/nx-flutter".
Source file "flutter-graphql-client" does not exist in the workspace.
    at getNonProjectFileData (/Users/jochemvanweelde/Repositories/Installation/node_modules/@nxrocks/common/node_modules/nx/src/project-graph/project-graph-builder.js:367:15)
    at getFileData (/Users/jochemvanweelde/Repositories/Installation/node_modules/@nxrocks/common/node_modules/nx/src/project-graph/project-graph-builder.js:378:9)
    at validateCommonDependencyRules (/Users/jochemvanweelde/Repositories/Installation/node_modules/@nxrocks/common/node_modules/nx/src/project-graph/project-graph-builder.js:333:13)
    at validateDependency (/Users/jochemvanweelde/Repositories/Installation/node_modules/@nxrocks/common/node_modules/nx/src/project-graph/project-graph-builder.js:314:5)
    at ProjectGraphBuilder.addDependency (/Users/jochemvanweelde/Repositories/Installation/node_modules/@nxrocks/common/node_modules/nx/src/project-graph/project-graph-builder.js:191:9)
    at getProjectGraph (/Users/jochemvanweelde/Repositories/Installation/node_modules/@nxrocks/common/src/lib/workspace/project-graph.js:81:17)
    at Object.processProjectGraph (/Users/jochemvanweelde/Repositories/Installation/node_modules/@nxrocks/nx-flutter/src/project-graph.js:8:41)
    at /Users/jochemvanweelde/Repositories/Installation/node_modules/nx/src/project-graph/build-project-graph.js:138:42
    at Generator.next (<anonymous>)
    at fulfilled (/Users/jochemvanweelde/Repositories/Installation/node_modules/tslib/tslib.js:166:62)
```

## When running without local dependencies listed pubspec
```
>  NX  Falling back to ts-node for local typescript execution. This may be a little slower.
  - To fix this, ensure @swc-node/register and @swc/core have been installed

 >  NX   Report complete - copy this into the issue template

   Node   : 18.17.0
   OS     : darwin-arm64
   npm    : 10.8.2
   
   nx                 : 16.7.2
   @nx/js             : 16.7.2
   @nx/jest           : 16.7.2
   @nx/linter         : 16.7.2
   @nx/workspace      : 16.7.2
   @nx/cypress        : 16.7.2
   @nx/detox          : 16.7.2
   @nx/devkit         : 16.7.2
   @nx/eslint-plugin  : 16.7.2
   @nx/next           : 16.7.2
   @nx/node           : 16.7.2
   @nx/react          : 16.7.2
   @nrwl/tao          : 16.7.2
   @nx/web            : 16.7.2
   nx-cloud           : 16.0.5
   typescript         : 5.0.3
   ---------------------------------------
   Community plugins:
   @nxlv/python        : 16.3.1
   @nxrocks/nx-flutter : 7.1.0
```

### Expected Behaviour

1. Create flutter application
2. Create flutter library
3. Add local flutter package dependency in pubspec of app or other library
4. run any nx command

### Actual Behaviour

1. Create flutter application
2. Create flutter library
3. Add local flutter package dependency in pubspec of app or other library
4. Not being able to run any nx command since the graph cannot be generated 

### Steps to reproduce the behaviour

1. Create flutter application (using generator)
2. Create flutter library (using generator)
3. Add flutter library dependency in pubspec of app or other library
```yaml
dependencies:
  flutter_test_lib:
    path: ../test-lib
```
4. run any nx command

Also something interesting to note is that the generator will modify the nx.json file and break it:
```json
"plugins": [
    "@nxrocks/nx-flutter",
    "@nxlv/python",
    {}
  ]
```
The {} object is added and nx will break, removing it fixes the issue.

After removing the object and adding the local dependency in pubspec the following error returns when running nx report:
```
 Failed to process the project graph with "@nxrocks/nx-flutter".

   Source file "flutter-test-lib" does not exist in the workspace.
```

My project is structured like this:
```
├── apps/
│   └── flutter-app/
│       └── pubspec.yaml
└── libs/
    ├── flutter/
    │   ├── some-lib/
    │   │   └── pubspec.yaml
    │   └── some-other-lib/
    │       └── pubspec.yaml
    └── some-non-flutter-lib
```

**Comment by tinesoft** [comment]
Hi @jochemvanweelde 

Thanks for using the plugin.

I see you are on a old version though (`v7.1.0`), can you try migrating to the latest version and retry?

`nx migrate @nxrocks/nx-flutter latest`  
or update the `package.json` directly and reinstall deps

**Comment by jochemvanweelde** [comment]
Hi @tinesoft 

Thanks for your quick reply.

Our monorepo is quite large and upgrading nx is hard for us to do due to all kinds of peer-dependancies. 

upgrading nx-flutter requires us to use a newer major version of @nx/devkit which requires us to upgrade all the nx dependencies. 

When migrating nx to a new version I need to run npm install with the --legacy-peer-deps flag to get it working, introducing potential breaking changes throughout the monorepo. Though, after upgrading, it does seem to be working. 

However upgrading results in lots of testing, well... everything. 
Another solution or cause to this problem would help me out so much.

**Comment by tinesoft** [comment]
Hi @jochemvanweelde 

You are **3 major versions of Nx behind** and  **2 major versions of Nx-flutter behind**, which make supporting you very hard (as I'm sure you understand), given the amount of breaking changes and new features (from Nx), on top of which my nx-flutter plugin now relies on.


- Are you using other tech stack other than Nx flutter?  (in other words, what makes updating your nx workspace complicated? The large size of it is not really an issue, with the powerfull `nx migrate` command)
- Have you try upgrading each major Nx version at the time ? ( `nx migrate nx@17` -> `nx migrate nx@18`  -> `nx migrate nx@latest` ), that way you reduce the amount of potential issues you can face during the update process
- Having to run npm install with the `--legacy-peer-deps` is **suspicious** and reflects a bad/incompatible version dependency used at some point...

Another potential solution would be to debug the execution of the `nx <flutter-command> <flutter-project>` (easy in VSCode: simply run the command in the `Javascript Debug Terminal` , locate the "<flutter-command>" executor in your node_modules (`node_modules/@nxrocks/nx-flutter/src/executors/clean/executor.js` for example) and add a breakpoint in it

Then you could create patch of the library that fixes the issue and use it instead (easy with `pnpm` or via [patch-package](https://www.npmjs.com/package/patch-package)
 
You can DM me in private on [Nx Discord channel](https://go.nx.dev/community), so I can have a look on your project and assist you more in the process. Other than that, I hardly seem how I can help you more.
