### ISSUE TITLE
[Feature] Flutter Pub Command

### ISSUE THREAD

**Issue by denny99** [tinesoft/nxrocks#234]
### Is your feature request related to a problem? Please describe

With the new fix i wanted to update our pipelines to use only nx commands to build our flutter app.
The pipeline uses two commands that might not be possible right now with the plugin:

flutter pub run build_runner build 
flutter pub run flutter_launcher_icons:main

### Describe the idea you'd like

It would be nice to be able to use the flutter pub command directly from nx

### Describe alternatives you've considered

Right now im using a specific working directory to execute the pub commands. 
With multiple projects this won't work.

**Comment by tinesoft** [comment]
Done in https://github.com/tinesoft/nxrocks/releases/tag/nx-flutter%2Fv9.3.0 !

the syntax to run your pub commands above is:
```
$ nx pub-run your-flutterapp --executable="build_runner build"  

or

$ nx run your-flutterapp:pub-run --executabe="build_runner build" 
```
>  💡 Note  the "" around the executable command, because it has spaces


See [README.md](https://github.com/tinesoft/nxrocks/blob/develop/packages/nx-flutter/README.md#executors) for all the commands

**Comment by denny99** [comment]
Tine you're awesome! :)

But i think you broke the package for regular npm users.

npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "workspace:": workspace:*

Might be related to your changes of the dependencies

**Comment by tinesoft** [comment]
Which package manager are you using? if  not NPM
Is the installation working for that package manager ?

**Comment by denny99** [comment]
ERR_PNPM_WORKSPACE_PKG_NOT_FOUND  In : "@nxrocks/common@workspace:*" is in the dependencies but no package named "@nxrocks/common" is present in the workspace
 
 This is the error with pnpm.

**Comment by denny99** [comment]
Yarn is smart enough to ask me, which versions i want to use, as it cannot resolve the version either

**Comment by tinesoft** [comment]
FIxed in latest  https://github.com/tinesoft/nxrocks/releases/tag/nx-flutter%2Fv9.3.1
