### ISSUE TITLE
[Bug] Unsupported URL Type error when installing

### ISSUE THREAD

**Issue by jbrischle** [tinesoft/nxrocks#235]
### Plugin Name

@nxrocks/nx-spring-boot

### Nx Report

No nx report available
### Expected Behaviour

Inststallatin works.

### Actual Behaviour

Install doesn't work.

### Steps to reproduce the behaviour

1. package.json:
`
{
  "name": "node-starter",
  "private": true,
  "dependencies": {
    "@nxrocks/nx-spring-boot": "10.2.5",
    "nx": "19.5.7"
  }
}
`
2. Run npm install

> npm ERR! code EUNSUPPORTEDPROTOCOL
> npm ERR! Unsupported URL Type "workspace:": workspace:*
> npm ERR! A complete log of this run can be found in: /home/.npm/_logs/2024-08-09T09_07_40_960Z-debug-0.log

### Hint
Version 10.2.4 works

**Comment by tinesoft** [comment]
Fixed and released in latest https://github.com/tinesoft/nxrocks/releases/tag/nx-spring-boot%2Fv10.2.6
