### ISSUE TITLE
[Feature] [nx-flutter] add dependency graph support 

### ISSUE THREAD

**Issue by tinesoft** [tinesoft/nxrocks#28]
**Is your feature request related to a problem? Please describe.**
It would be great if the plugin could generate the dependency graph for the flutter packages used
by analysing imports or reading the `pubspec.yaml` for example...

**Describe the idea you'd like**

**Describe alternatives you've considered**

**Additional context**
Investigate how Nx does it for TS/JS code

**Comment by AgentEnder** [comment]
For further context, here is what the implementation in my nx-dotnet plugin looks like:

https://github.com/nx-dotnet/nx-dotnet/blob/master/packages/core/src/graph/process-project-graph.ts
https://github.com/nx-dotnet/nx-dotnet/blob/master/packages/utils/src/lib/workspace.ts

**Comment by tinesoft** [comment]
Hi @AgentEnder ,

Thanks for Nx 12 and the extension point added to the [project graph API](https://nx.dev/latest/angular/structure/project-graph-plugins), I was able to solve this issue already ( I have yet to push the changes).

This should be released in the next upcoming version of the plugin (`v2.1.0`) very shortly. Stay tuned ;-)



Thanks for the pointer anyway!

**Comment by AgentEnder** [comment]
Great! The nx-dotnet plugin is also making use of the project graph API.

**Comment by tinesoft** [comment]
Yes exactly. This kind of extension was not possible prior Nx12 .

**Comment by AgentEnder** [comment]
Yes, its very exciting to see this part of Nx opening up. Makes it much more useful in non JS/TS workspaces.

**Comment by tinesoft** [comment]
@AgentEnder  I cannot agree more! 😊
I've been waiting for this feature since this issue was created!
