### ISSUE TITLE
[Feature] Add a Test target to springboot app schematic

### ISSUE THREAD

**Issue by Kwandes** [tinesoft/nxrocks#30]
**Is your feature request related to a problem? Please describe.**
Applications in NX projects usually include a `test` target, for running tests for the given application. That is missing from the schematic for a springboot app.
It could utilize `mvnw test` to perform testing. This would be faster than the current alternative which is to build a jar/war, and isolates issues.

**Describe the idea you'd like**
A test target included in the generated code, which runs `mvn test` or some form of it. Triggered when `nx test app` and `nx run-many --all --target=test` is run.

**Describe alternatives you've considered**
I can trigger the tests via the buildJar command, but that takes longer, and produces extra artefacts, making it less suitable for Continous Integration.
I can also navigate to the app directory and run `mvn test` manually, but that defeats the purpose of nx

**Additional context**
This would come very useful during Continous Integration. Currently, I need to write a special workflow step for testing the java app, instead of having it be run along with all other apps with `nx run-many --all --target=test`.
It also bypasses NX Cloud cache, although that is less of a concern

**Comment by tinesoft** [comment]
Hi @Kwandes 

Great  idea 💡 ! I will start implementing it ASAP.

Cheers
