### ISSUE TITLE
Support provided Maven/Gradle runtimes

### ISSUE THREAD

**Issue by jbadeau** [tinesoft/nxrocks#31]
Support host provided Maven and Gradle runtimes.

It would be great if this plugin could support host provided Maven and Gradle runtimes in addition to wrappers to provide:

- Firewalled support (i.e. cant download wrappers)
- Consistent runtime versions (always the same version of maven or gradle)
- Faster
- Better support for CI steps

**Comment by tinesoft** [comment]
Hi @jbadeau 

Thanks for submitting the idea.

Can you elaborate what you mean by "host provided runtimes"?
and how you would like to specify them?

Cheers

**Comment by jbadeau** [comment]
The builders rely on the wrappers 'mvnw' and 'gradlew' which are not always existing (coudlnot download for instance).

I just did a quick test by changing the command

`./mvnw${isWin ? '.cmd' : ''}`; 

to

`mvn`;

which works fine. A builder option for ignoreWrapper would be great.

**Comment by tinesoft** [comment]
Ok I get it now. Thanks for clarifying.

It is indeed a legit improvement.


I will start implementing that soon.

**Comment by jbadeau** [comment]
Awesome! And great job on the plug-in :)

**Comment by jbadeau** [comment]
Cool, will try out today.

Will also have a look at the dependency and caching later this week.
