### ISSUE TITLE
Dependencies Question

### ISSUE THREAD

**Issue by jbadeau** [tinesoft/nxrocks#32]
Currently the spring integration only supports a single module and not dependencies (at least in maven).

Do you have any plans to support dependencies (e.g. foo-common)

- How would this work?
- Would it use maven reactor or nx dependency graph`?
- How would this work with nx build cache and affected:apps/libs

If these are not planned I could have a look at it

**Comment by tinesoft** [comment]
Hi @jbadeau

Thanks for the question.

By "dependencies", you mean being able to see how multiple spring-boot projects (apps or libraries) inside the Nx workspace are related, right? Just like Nx does it for Angular or React projects ?

If so, this could be indeed a great 💡 addition to the plugin.

I will have to dig into how Nx team does it for Angular or React projects when running `nx dep-graph`... But in the meantime, if you want to contribute with an initial PR, feel free to submit 😄 

Cheers

**Comment by tinesoft** [comment]
Fixed in https://github.com/tinesoft/nxrocks/pull/51 and released in `v2.1.0`

**Comment by SOG-web** [comment]
Hi please have you been able to come up with a solution for this dep graph
