### ISSUE TITLE
[Bug] generate new app not working with Nx 11.2

### ISSUE THREAD

**Issue by DominikPieper** [tinesoft/nxrocks#37]
Plugin Name and Version:
nx-spring-boot@v1.3.0

Nx Version (`nx --version`):

Nx 11.2.0

Angular CLI version (`ng --version`):

#### Expected Behaviour
Project is generated

#### Actual Behaviour
In the actual Nx version 11.2 the import @nrwl/workspace/src/utils/fileutils changed  to @nrwl/workspace/src/utilities/fileutils

#### Steps to reproduce the behaviour
Just try to generate a new application in a Nx 11.2 workspace

**Comment by tinesoft** [comment]
Hi @DominikPieper 

Thank you for reporting the issue.
I will have a look asap.


Cheers

**Comment by DominikPieper** [comment]
Great, thanks. The solution is just the change of the import. Did the same fix for my Nx plugin. They renamed the folder
