### ISSUE TITLE
[Bug] not able to create module and Shareable Flutter project containing modular Dart code

### ISSUE THREAD

**Issue by dhrn** [tinesoft/nxrocks#44]
Plugin Name and Version:

nx-flutter

Nx Version (`nx --version`):
11.5.1

Angular CLI version (`ng --version`):
11.5.1

#### Expected Behaviour
should be able to create
...

#### Actual Behaviour
![image](https://user-images.githubusercontent.com/14145706/111141275-5b243980-85a9-11eb-8b3b-2701445144fd.png)
...

#### Steps to reproduce the behaviour

Try to scaffold the `Flutter module ` and `Shareable Flutter project containing modular Dart code `

**Comment by tinesoft** [comment]
Hi @dhrn 

Thanks for using the plugin and for reporting this.
I will a look asap and provide  a fix soon.
