### ISSUE TITLE
[Feature] Some more working code in the generated app

### ISSUE THREAD

**Issue by trumbitta** [tinesoft/nxrocks#5]
Both the express and NestJS app generator schematics produce an app with a simple working REST endpoint: some `GET /api/v1/example` with a simple JSON response body.

I think this is something the spring boot plugin should also do, because it empowers newbies giving them some sort of track to follow.

It would also greatly simplify some Nx demo I'm working on :D

**Comment by tinesoft** [comment]
Hi,

Humm...it is a bit opinionated, as not all applications generated are necessary "web" applications, but I see the point.

Maybe this can be solved by using concept of presets, just like Nx do when generating a workspace...

This could be a new `preset` option to add to the `application` schematics, that would call a `preset` schematics.
Possible value can be: `empty` (current behavior) | `web` (with a basic REST endpoint).

I will see what i can do.

Stay tuned!
