### ISSUE TITLE
[Feature] [nx-spring-boot] nx affected:build should build changed spring boot project.

### ISSUE THREAD

**Issue by CodingSpiderFox** [tinesoft/nxrocks#53]
Plugin Name and Version:
"@nxrocks/nx-spring-boot": "2.1.0"

Nx Version (`nx --version`):
12.0.8

Angular CLI version (`ng --version`):
React 17.0.2.

#### Expected Behaviour
`nx affected:build --all should rebuild spring boot project 

#### Actual Behaviour
Output is: (note abcd is the React application)
```
nx affected:build --all                                                                             ✔  13:34:17   

>  NX   WARNING  Running affected:* commands with --all can result in very slow builds.

  --all is not meant to be used for any sizable project or to be used in CI.
  
  Learn more about checking only what is affected: https://nx.dev/latest/angular/cli/affected#affected.


>  NX  Running target build for projects:

  - abcd
```

#### Steps to reproduce the behaviour
Create workspace with a react application
Add nx-spring-boot and create an app project with nx-spring boot 

npm install @nxrocks/nx-spring-boot --save-dev
nx g @nxrocks/nx-spring-boot:new my-app

Commit everything to master branch

Checkout new branch and add a line "System.out.println();" to the Spring Application main method
Commit to the branch

run `nx affected:build --all` 

It should rebuild the Spring App but it doesnt

**Comment by tinesoft** [comment]
Hi @CodingSpiderFox 

Thanks for using the plugin and for opening an issue!

What you are asking is more a feature than a bug actually.
In fact, there is currently no "build" executor/builder out-of-the box for the `nx-spring-boot` plugin
(its either `buildJar` or `buildWar`).
Also, the behavior you natively have with nx's`affected`commands on JS/TS-based projects, must be
explicitly implemented for non JS/TS-based projects like Spring Boot's.

This is a valid improvement though, I will look into it.

Stay tuned!

**Comment by CodingSpiderFox** [comment]
Thanks :)

**Comment by tinesoft** [comment]
Fixed since https://github.com/tinesoft/nxrocks/releases/tag/nx-spring-boot%2Fv4.0.0
