### ISSUE TITLE
[Bug] CLI generator stuck when asking for user input

### ISSUE THREAD

**Issue by trumbitta** [tinesoft/nxrocks#6]
Plugin Version:
latest from NPM

Nx Version (`nx --version`):
10.3.1

#### Expected Behaviour

When generating a new app, all the input prompts work.

#### Actual Behaviour

When generating a new app, some input prompts don't work and script is stuck. E.g. when asked which type of project I want, the "enter" keys does nothing with either the default value or after typing `gradle-project` or `maven-project`.  
Some other prompts have the same behavior, some don't.

#### Steps to reproduce the behaviour

Try to generate a new app from the CLI, in interactive mode.

**Comment by tinesoft** [comment]
Thanks for reporting @trumbitta 

Will look into it asap.

In the meantime, if you found out the cause of this issue, please don't hesitate to share it

Cheers!
