### ISSUE TITLE
[Feature]  How can I create a lib and use in an application?

### ISSUE THREAD

**Issue by andre-silvakmm** [tinesoft/nxrocks#65]
Can I create a spring-boot library and use inside a application in the workspace?

**Comment by tinesoft** [comment]
Sure, since [v2.0.0](https://github.com/tinesoft/nxrocks/releases/tag/nx-spring-boot%2Fv2.0.0) of the plugin you can.

Simply run:

`nx g @nxrocks/nx-spring-boot my-boot-lib` and choose `Library` when prompted for the type of project

You can also directly run:

`nx g @nxrocks/nx-spring-boot my-boot-lib --library`

**Comment by andre-silvakmm** [comment]
Sorry for reopen the question but, I already have the lib and already have the application in the workspace, I'm wondering in how to use that lib in the workspace application similarly in the way of angular lib of nx workspace, is that possible, or I have to local map that lib with maven?

**Comment by tinesoft** [comment]
I'm not sure I follow you... just add the dependency of your library in the `pom.xml` (or `build.gradle`) of the application that needs it, just as a regular maven/gradle project.

**Comment by andre-silvakmm** [comment]
I have added in the pom.xml, but it was not found by maven.
It gives me erro when I try to run.

**Comment by tinesoft** [comment]
As your library is not published yet, you have to locally install it so it can be visible by your app.
You must run `mvn install` from the library root folder to do so.

**Comment by andre-silvakmm** [comment]
Perfect, works like a charm.
Thnx for you time.

**Comment by tinesoft** [comment]
No problem!


I will look into a way to automate this, i.e auto-install dependencies (libraries) of a Spring Boot app inside the workspace when running|building the app itself via `nx serve your-boot-app`.
I've created https://github.com/tinesoft/nxrocks/issues/66 to track that

**Comment by while1618** [comment]
Are there any examples of how apps and libs work together in nx-spring-boot?

I don't see the point of libs right now, it's like a separated app. In my case, I have an app with the following packages: "admin, auth, user, shared". I want to divide them into separated libs and use them in the app, but I can't find a way in doing that. I can't even import the class from lib to app.

Also, is there a way to have just one pom.xml in the main app, and that libs will read from it, like in angular for example? You have one main package.json, and all libs and apps can read from that one package.json.

**Comment by ZdenekMerta** [comment]
It would be useful to add the same feature to `nx-quarkus` package.
