### ISSUE TITLE
[Bug] nx print-affected logs debug message which results to a non parseable json

### ISSUE THREAD

**Issue by WtfJoke** [tinesoft/nxrocks#68]
Plugin Name and Version:
nx-spring-boot@2.1.0

Nx Version (`nx --version`):

12.5.6

Angular CLI version (`ng --version`):

#### Expected Behaviour

When I run `nx print-affected --base HEAD~1 --target deploy`  I expect a json parseable output.

Like:
```json
{
  "tasks": [
    {
      "id": "sample:deploy",
      "overrides": {},
      "target": {
        "project": "sample",
        "target": "deploy"
      },
      "command": "yarn nx deploy sample",
      "outputs": []
    },
```

#### Actual Behaviour

When I run `nx print-affected --base HEAD~1 --target deploy`  I get:
```
[nx-spring-boot]: Looking Spring Boot related projects inside the workspace...
[nx-spring-boot]: Adding dependencies for project 'sample'...
{
  "tasks": [],
  "projects": [
    "github-pipelines",
```

#### Steps to reproduce the behaviour

1. Run `nx print-affected --base HEAD~1 --target build`
2. See non parseable json output

Strangely enough this is only on first execution. 

Is there the possibility to delete these debug log lines? Or only log if a log level debug is enabled. Or verbose logging is enabled?

**Comment by tinesoft** [comment]
Hi @WtfJoke,

Sorry for the delay in responding.
I agree the logs are not really relevant and should be removed (or at least wrap under a "verbose" option).
Will do that in the upcoming release of the plugin.
Stay tuned!

**Comment by WtfJoke** [comment]
Hi @tinesoft 

Thanks! Our CI will thank you too :D
Looking forward to the upcoming release
