### ISSUE TITLE
[Feature] Convert current issue templates into issue forms

### ISSUE THREAD

**Issue by tinesoft** [tinesoft/nxrocks#78]
Github introduced **Issue Forms** a moment ago (still in beta though).
It is a better alternative to  static **Issue Templates** (in Markdown), as they
allow to better describe and above all, validate the information that must/should be provided when creating an new bug report or feature request.

Please convert the current templates under `.github/ISSUE_TEMPLATE/*` into this new format (YAML).

This might help: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms

**Comment by aneeshrelan** [comment]
Hey, can I take a shot at this?

**Comment by tinesoft** [comment]
Hi @aneeshrelan 

Sure! Please be my guest!

And thanks for helping out 😊
