### ISSUE TITLE
Using consistent naming

### ISSUE THREAD

**Issue by trumbitta** [tinesoft/nxrocks#8]
I'd like to see a consistent (hence mnemonic) naming for the targets, just like for the official plugins by Nrwl.

## Example

Instead of: `nx run myApp:run`
Have this: `nx run myApp:serve`

I'm still on the fence about the others, but this one bugs me in a special way :D

**Comment by tinesoft** [comment]
Hi @trumbitta 

Whoa, thanks you for all you feedbacks! Very much appreciated.
This is indeed a valid point. Plus, this will make #7 unnecessary (as a simple `nx serve my-boot-app` will suffice).

I will make change asap.


Cheers!

**Comment by trumbitta** [comment]
Awesome idea! 👏
