### ISSUE TITLE
Release including the buildJar/buildWar to build change

### ISSUE THREAD

**Issue by sidyes** [tinesoft/nxrocks#89]
### Is your feature request related to a problem? Please describe

At the moment I cannot use the `buildJar` target as I need the `package` mvn command to be run first (cf. #43).

### Describe the idea you'd like

Could you release the current development branch please?

### Describe alternatives you've considered

Implementing my own targets which would be not necessary.

**Comment by tinesoft** [comment]
Hi @sidyes 

Thanks for your interest in the plugin!

The next release is coming very soon 🙂.
I want to include a couple of long-awaited features along with it.

The dev are being finalized, this shouldn't take much long now.

Stay tuned !

**Comment by tinesoft** [comment]
released in https://github.com/tinesoft/nxrocks/releases/tag/nx-spring-boot%2Fv4.0.0
