### ISSUE TITLE
4.0.0 release not working // npm i fails

### ISSUE THREAD

**Issue by sidyes** [tinesoft/nxrocks#95]
> released in https://github.com/tinesoft/nxrocks/releases/tag/nx-spring-boot%2Fv4.0.0

Unfortunately, it is not working. `npm i @nxrocks/nx-spring-boot` leads to the following error message:

```
No matching version found for @nxrocks/common@0.0.0-development.
```

Can you please fix that?

_Originally posted by @sidyes in https://github.com/tinesoft/nxrocks/issues/89#issuecomment-1039014741_

**Comment by tinesoft** [comment]
Hi @sidyes 

Thanks for reporting. This should now be fixed by https://github.com/tinesoft/nxrocks/releases/tag/nx-spring-boot%2Fv4.0.2

Please try again, and feel free to re-open if still having the issue
