### ISSUE TITLE
[Bug] unable to install plugin with npm i @nxrocks/nx-quarkus --save-dev

### ISSUE THREAD

**Issue by ctientcheu** [tinesoft/nxrocks#96]
### Plugin Name

@nxrocks/nx-quarkus

### Plugin Version

v2.1.1

### Nx Version

13.8.1

### Expected Behaviour

the plugin package to be installed

### Actual Behaviour

> npm i @nxrocks/nx-spring-boot --save-dev
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @nxrocks/common@0.0.0-development.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ctientcheu/.npm/_logs/2022-02-16T19_00_47_104Z-debug.log

### Steps to reproduce the behaviour

1- create a nx monorepo using npx
2- run 'npm i @nxrocks/nx-quarkus --save-dev'

**Comment by tinesoft** [comment]
This should now be fixed by https://github.com/tinesoft/nxrocks/releases/tag/nx-quarkus%2Fv2.1.2
Please try again, and feel free to re-open if still having the issue
