### ISSUE TITLE
[Bug] [nx-quarkus] `Premature close` when generating project

### ISSUE THREAD

**Issue by rsvoboda** [tinesoft/nxrocks#97]
### Plugin Name

@nxrocks/nx-quarkus

### Plugin Version

2.1.2

### Nx Version

13.8.3

### Expected Behaviour

`nx g @nxrocks/nx-quarkus:new abc` ends without error, app gets generated

### Actual Behaviour

`nx g @nxrocks/nx-quarkus:new abc` ends with error

### Steps to reproduce the behaviour

Follow https://github.com/tinesoft/nxrocks/tree/develop/packages/nx-quarkus#getting-started

I can generate Quarkus project when I manually edit `./node_modules/@nxrocks/nx-quarkus/src/generators/project/lib/generate-quarkus-project.js` and comment out `throw e_1.error;` line.
Generated project works fine, I'm able to run commands like `nx package abc`.

I tried to get the zip using curl and extract it using jar and all worked fine. Downloaded zip doesn't seem to be corrupted.
`curl -sS https://code.quarkus.io/d\?b\=MAVEN\&g\=com.example\&a\=demo\&e\=io.quarkus:quarkus-resteasy-jackson | jar xv`

**Comment by tinesoft** [comment]
Hi @rsvoboda ,

Thanks for using the  plugin and for reporting this. I'll look into it asap

**Comment by loic-roux-404** [comment]
same issue with spring

Zip stream aren't closed correctly i think https://stackoverflow.com/questions/55959479/error-err-stream-premature-close-premature-close-in-node-pipeline-stream

**Comment by tinesoft** [comment]
Thanks for your comment @loic-roux-404 , it seems related to https://github.com/ZJONSSON/node-unzipper/issues/228 ( I use that library `Unzipper` internally, to do the unzipping).

I will search for a proper fix or a workaround.

**Comment by rsvoboda** [comment]
`node -v` gives v17.4.0

**Comment by tinesoft** [comment]
Thanks for the confirmation. That will  help narrowing where to look for for a possible fix.

**Comment by tinesoft** [comment]
Hi,

I'm still investigating on how to solve this  issue... In the meantime, sticking to Nodejs LTS (v16 at the time) , if possible, should avoid the error to happen.
